# Generated by Django 4.0.1 on 2022-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VebinarMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
