# Generated by Django 4.0.1 on 2022-11-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_vebinarmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=80)),
                ('progress', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Опубликовано:')),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=10000)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='outsource.case')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='case_images/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outsource.case')),
            ],
        ),
    ]
