# Generated by Django 4.0.1 on 2022-11-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0003_case_paragraph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
