# Generated by Django 4.0.1 on 2022-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_alter_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='author_images/'),
        ),
    ]
