# Generated by Django 4.0.1 on 2022-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_case_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='long',
            field=models.CharField(default='5 мин. чтения', max_length=30),
        ),
    ]
