# Generated by Django 4.0.1 on 2022-11-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0006_case_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outsource.paragraph'),
        ),
    ]
