# Generated by Django 4.0.1 on 2022-11-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0007_alter_image_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='case',
        ),
    ]
