# Generated by Django 4.0.1 on 2022-11-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0009_image_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='paragraph',
        ),
    ]
