# Generated by Django 4.0.1 on 2022-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0013_alter_paragraph_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='views',
        ),
        migrations.AddField(
            model_name='case',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='case_views', to='outsource.Ip'),
        ),
    ]
