# Generated by Django 4.0.1 on 2022-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0019_case_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='views',
        ),
        migrations.AddField(
            model_name='case',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='case_views', to='outsource.Ip'),
        ),
    ]
